### ISSUE TITLE
Ručni unos korisnika

### ISSUE THREAD

**Issue by speedz3107** [rmunk/EleventhHour#34]
U planeru dodati opciju dodavanja korisnika i pregleda korisnika.,

**Comment by speedz3107** [comment]
priority:urgent

**Comment by rmunk** [comment]
Sta je sa korisnicima koji dolaze preko 5do12, jel se oni automatski dodaju u listu korisnika ili ih provider sam dodaje u listu?

**Comment by speedz3107** [comment]
Oni se automatski dodaju, njihovi profili kao korisnici.
